run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - misspell
    - revive
    - gofmt

linters-settings:
  revive:
    rules:
      - name: blank-imports
      - name: exported
      - name: var-naming
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: error-return
      - name: error-strings
      - name: unexported-return

issues:
  exclude-dirs:
    - examples
